### ISSUE TITLE
[RFE] Enable using of adjust at any level

### ISSUE THREAD

**Issue by kkaarreell** [teemtee/fmf#157]
In my current test plan I am using `adjust` to modify both `prepare` and `discover`
https://github.com/keylime/keylime/blob/master/packit-ci.fmf

It is still quite short and therefore readable but it seems to me that with more conditions in `adjust` block things would become a bit more messy. I think it would be more user friendly if I could have one `adjust` inside the `prepare` step and another `adjust` in `discover`.

**Comment by kkaarreell** [comment]
So it could be more like this:
```
/e2e:
  summary: run keylime e2e tests

  prepare:
    how: shell
    script: 
     - ln -s $(pwd) /var/tmp/keylime_sources

    adjust:
     - when: distro == centos-stream-9
       script+: 
        - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm

     - when: distro == centos-stream-8
       script+: 
        - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

  discover:
    how: fmf
    url: https://github.com/RedHat-SP-Security/keylime-tests
    ref: main
    test: 
     - /setup/configure_tpm_emulator
     - /setup/install_upstream_keylime
     - /setup/enable_keylime_coverage
     - /functional/basic-attestation-on-localhost
     - /setup/generate_coverage_report

    adjust:
     - when: distro != fedora-35
       test-:
        - /setup/enable_keylime_coverage
        - /setup/generate_coverage_report

  execute:
    how: tmt

```
