### ISSUE TITLE
Merging for nested dictionaries defined in root

### ISSUE THREAD

**Issue by lukaszachy** [teemtee/fmf#190]
Based on the promises of Elasticity and Merging I'd expect this fmf file (either main.fmf or arbitrary name in the fmf root)
```yaml
a+:
  b+:
    c: d
```
to produce `'a': {'b': {'c': 'd'}`  dictionary. However currently 'a+' and 'b+' is kept as key names.

Also the 
```yaml
foo: bar

/child:
    a+:
        b+:
            c: d
``` 
keeps 'b+' as key name (the 'a' is correctly named.)

Would be nice if one can use Merging everywhere in the Tree structure.

**Comment by jscotka** [comment]
Should work well as we've introduced. Probably some feature break this behaviour. I remember I've implemented it in https://github.com/teemtee/fmf/pull/93

**Comment by kkaarreell** [comment]
> Should work well as we've introduced. Probably some feature break this behaviour. I remember I've implemented it in #93

Your test is still working, however the major difference here is that in your test the non-plus attribute exists while in the example above there is no `a` attribute to extend.

What works is:
```
$ cat main.fmf
a: {}

/child:
    a+:
        b+:
            c: d

$ fmf show
/child
a: {'b': {'c': 'd'}}
```

**Comment by psss** [comment]
Reopening as fix in #263 caused a regression #276 and after the revert hotfix #279 we need a proper solution. One possible approach could be to allow selecting keys under which the suffix removal should not happen. In this way anything which is stored under the `adjust` key could be preserved and the adjust rules could still contain `key+` syntax unchanged.

If we go this way, the list of such keys has to be provided when initializing the `fmf` tree, because the merging and key handling is performed during the tree discovery. We could default to include the `adjust` key there so that the most common use case is covered (we already default to `adjust` in the `Tree.adjust()` method), or we could keep the list empty and leave this on the user.

**Comment by kkaarreell** [comment]
Hi @psss , could you please describe what is the issue with the current state? I am sorry, maybe I wasn't following all discussions but it is not clear to me what we are trying to address now. Thank you.

**Comment by psss** [comment]
Sure, the problem is the original issue: When a `key+` is used deeper in the structure, the suffix is not removed unless the key was already defined in the parent and inherited: Here's a simple example:

```yaml
one+:
    two+:
        three+:
            key: value
```

The outcome would be:

```
> fmf show
/
one: {'two+': {'three+': {'key': 'value'}}}
```

Note that the `+` suffix is correctly stripped from `one` but not from `two` and `three`. A tangible example from `tmt` could be extending a hardware requirement in a plan which may but does not have to inherit from a parent plan:

```yaml
provision+:
    how: virtual
    hardware+:
        memory: 12 GB
execute:    
    how: tmt
```

The suffix is not stripped from the `hardware` key and thus it does not match the expected schema:

```
> tmt plan show plan
    warn: /plan:provision - {'how': 'virtual', 'hardware+': {'memory': '12 GB'}} is not valid under any of the given schemas
/plan
                 enabled true
```

Hope this makes it more clear.

**Comment by psss** [comment]
@bgoncalv, just to clarify your use case with extending the `hardware` requirements: The `adjust` would work even if the `hardware` key is not defined in the parent:

```yaml
discover:
    how: fmf
execute:
    how: tmt
provision:
    how: artemis
      
/bare:
    adjust:
      - when: package-name ~= kernel-64k
        provision+:
            hardware+:
                virtualization:
                    is-virtualized: false
```

It would work nice also when the `hardware` key is defined:

```yaml
discover:
    how: fmf
execute:
    how: tmt
provision:
    how: artemis
    hardware:
        memory: 12 GB

/bare:
    adjust:
      - when: package-name ~= kernel-64k
        provision+:
            hardware+:
                virtualization:
                    is-virtualized: false
```

But would not work if the `hardware` key in the parent node has the suffix:

```yaml
discover:
    how: fmf
execute:
    how: tmt
provision:
    how: artemis
    hardware+:
        memory: 12 GB

/bare:
    adjust:
      - when: package-name ~= kernel-64k
        provision+:
            hardware+:
                virtualization:
                    is-virtualized: false
```

It would complain about an invalid key:

```
warn: /bruno/bare:provision - {'how': 'artemis', 'hardware+': {'memory': '12 GB'}, 'hardware': {'virtualization': {'is-virtualized': False}}} is not valid under any of the given schemas
```
