### ISSUE TITLE
Inconsistent order of operations

### ISSUE THREAD

**Issue by LecrisUT** [teemtee/fmf#232]
Example:
```yaml
my_var:
  - one
  - two

/overwrite:
  my_var-: [ two, three ]
  my_var+: [ three, four ]
```

This one gives `my_var: one and four` which would be inconsistent based on the order of definition. This might not be that crucial, but at least it should be documented that the keys are ordered before being parsed by fmf, thus the order is ...

Are there tests at least covering the operation order based on inheritance (inherited operations occur first, e.g. if `my_var-:` was one level below, `three` should be in the list) and adjust (after base variable operations)?
